import type { Metadata } from "next";
import { spaceGrotesk } from './fonts'
import NavBar from "./components/NavBar";
import "./globals.css";

export const metadata: Metadata = {
  title: "swapi-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.className} antialiased`}>
        <NavBar/>
        {children}
        </body>
    </html>
  );
}
